#%RAML 1.0 NamedExample
  
  -
    employeeId: 0001
    employeeFirstName: Harshad
    employeeLastname: Patil
    DepartmentName: Support
    DepartmentId: 1234
    Phone: 987654321
    baseLocation: Banglore
    employeeSalary: 100k
  -
    employeeId: 0002
    employeeFirstName: Sumanth
    employeeLastname: Konduru
    DepartmentName: Support
    DepartmentId: 1234
    Phone: 987654322
    baseLocation: Hyderbad
    employeeSalary: 10k
