#%RAML 1.0 NamedExample

  employeeId: 0001
  employeeFirstName: Sumanth
  employeeLastname: Konduru
  DepartmentName: Support
  DepartmentId: 1234
  Phone: 987654321
  baseLocation: Hyderbad
  employeeSalary: 10k